// Parse the extracted paragraphs of 한국어 사고도구어 목록 (HWP-derived)
// and emit a structured JSON of unique headwords by grade.
//
// Pipeline:
//   1) python scripts/extract-hwp-text.py "<path-to-hwp>" _sago_paras.txt
//   2) node scripts/extract-sago.mjs
//
// Input:  ./_sago_paras.txt   (gitignored; regenerated by step 1)
// Output: src/data/sago-words.json
//
// Detection: a paragraph cur is a headword when:
//   - it is not a column header, cross-reference, or stop word
//   - its base does NOT continue the previous family
//   - its NEXT non-xref paragraph proves it is a lead:
//       (a) next starts with cur            → next extends or equals cur (HW)
//       (b) cur starts with next            → cur is a variant; next is HW (skip cur)
//       (c) suffix-stripped next starts with suffix-stripped cur → HW
// where stripping removes trailing digit homonym markers + 하다/되다 suffixes.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const SRC = resolve(root, "_sago_paras.txt");
const text = readFileSync(SRC, "utf8");

const paragraphs = text
  .split(/\r?\n/)
  .filter((l) => l.trim())
  .map((l) => {
    const m = l.match(/^\[(\d+)\]\s?(.*)$/);
    return m ? m[2] : l;
  });

const GRADE_HEADER = /^([1-4])등급\s*\d+개$/;
const sectionStarts = [];
paragraphs.forEach((p, i) => {
  const m = p.match(GRADE_HEADER);
  if (m) sectionStarts.push({ grade: Number(m[1]), index: i });
});
if (sectionStarts.length !== 4) {
  console.error(`Expected 4 grade sections, found ${sectionStarts.length}`);
  process.exit(1);
}

const COLUMN_HEADERS = new Set(["단어", "단어족", "참조"]);
const CROSS_REF_PREFIX = /^(유\)|반\)|참\))/;

const isXref = (s) => CROSS_REF_PREFIX.test(s.trim());
const isHeader = (s) => COLUMN_HEADERS.has(s.trim());
const isStopWord = (s) => s === "총합" || /^\d+개$/.test(s);

const stripDigit = (s) => s.replace(/\d+$/, "");
// Strip trailing 하다/되다 (variants are usually 하다/되다 forms).
const stripSuffixes = (s) =>
  s.replace(/(하다\/되다|되다\/하다|하다|되다)$/, "");

function splitHeadword(raw) {
  const m = raw.match(/^(.+?)(\d+)$/);
  if (m) return { word: m[1], suffix: Number(m[2]) };
  return { word: raw, suffix: null };
}

function parseSection(start, end, grade) {
  const out = [];
  let i = start + 1;
  while (i < end && isHeader(paragraphs[i])) i++;

  let currentBase = null; // suffix- and digit-stripped

  while (i < end) {
    const cur = (paragraphs[i] ?? "").trim();
    if (!cur || isStopWord(cur) || isHeader(cur)) {
      i++;
      continue;
    }
    if (isXref(cur)) {
      i++;
      continue;
    }

    const curStripD = stripDigit(cur);
    const curStripS = stripSuffixes(curStripD);

    // Family continuation?
    if (
      currentBase &&
      (curStripD.startsWith(currentBase) || curStripS.startsWith(currentBase))
    ) {
      i++;
      continue;
    }

    // Look ahead to the next non-xref paragraph.
    let j = i + 1;
    while (
      j < end &&
      (!paragraphs[j].trim() ||
        isXref(paragraphs[j]) ||
        isStopWord(paragraphs[j]) ||
        isHeader(paragraphs[j]))
    ) {
      j++;
    }

    let isHW = false;
    if (j < end) {
      const nxt = paragraphs[j].trim();
      const nxtStripD = stripDigit(nxt);
      const nxtStripS = stripSuffixes(nxtStripD);

      if (nxtStripD.startsWith(curStripD)) {
        isHW = true; // (a)
      } else if (curStripD.startsWith(nxtStripD)) {
        isHW = false; // (b) — cur is a variant appearing before its HW
      } else if (nxtStripS.startsWith(curStripS)) {
        isHW = true; // (c)
      }
    }

    if (isHW) {
      const { word, suffix } = splitHeadword(cur);
      out.push({ grade, word, suffix, raw: cur });
      currentBase = curStripS;
    }
    i++;
  }
  return out;
}

const allWords = [];
const counts = {};
const expected = { 1: 43, 2: 293, 3: 585, 4: 466 };

for (let s = 0; s < sectionStarts.length; s++) {
  const start = sectionStarts[s].index;
  const end =
    s + 1 < sectionStarts.length
      ? sectionStarts[s + 1].index
      : paragraphs.length;
  const grade = sectionStarts[s].grade;
  const words = parseSection(start, end, grade);
  counts[grade] = words.length;
  const mark = words.length === expected[grade] ? "✓" : "△";
  console.log(`Grade ${grade}: ${words.length} (expected ${expected[grade]}) ${mark}`);
  allWords.push(...words);
}

console.log(`\nTotal: ${allWords.length} (expected 1387)`);

const out = {
  source: "충청남도교육청 — 한국어 사고도구어 목록(1,387개)",
  definition:
    "사고 및 논리 전개 과정을 담당하는 단어로, 주요 내용을 파악하고 이해하는 언어 능력(의사소통) 신장의 기반이 되는 단어들",
  totals: {
    1: counts[1] ?? 0,
    2: counts[2] ?? 0,
    3: counts[3] ?? 0,
    4: counts[4] ?? 0,
    all: allWords.length,
  },
  notes: {
    grade1:
      "1급(43개): 구체적 사고를 표상하는 어휘 중심. 구체적 조작기(7~12세) 초반, 초등 1~4학년군.",
    grade2:
      "2급(293개): 추상적 어휘 비중이 늘어남. 구체적 조작기 후반, 초등 5~6학년군.",
    grade3:
      "3급(585개): 추상적 사고도구어가 급증. 추상적 조작기(12세~성인) 초반, 중학교.",
    grade4:
      "4급(466개): 매우 추상적인 사고도구어 중심. 추상적 조작기 안정기, 고등학교군.",
  },
  words: allWords,
};

const outPath = resolve(root, "src/data/sago-words.json");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, JSON.stringify(out, null, 2), "utf8");
console.log(`\n→ ${outPath}`);

// Print grade 1 sanity
const g1 = allWords.filter((w) => w.grade === 1);
console.log(`\nGrade 1 (${g1.length}): ${g1.map((w) => w.raw).join(", ")}`);
