// Convert the source xlsx into src/data/books-seed.json (and SQL upsert file).
// Usage: node scripts/xlsx-to-json.mjs [path-to-xlsx]
//
// Defaults to the path of the original 충남교육청 file in 카카오톡 받은 파일.
// Outputs:
//   - src/data/books-seed.json        (typed-friendly JSON for dev fallback)
//   - scripts/books-seed.sql           (Supabase-ready INSERT statements)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { read as xlsxRead, utils as xlsxUtils } from "xlsx";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const DEFAULT_XLSX =
  process.argv[2] ||
  "C:\\Users\\User\\Documents\\카카오톡 받은 파일\\온독지수_도서_책소개_네이버_표지포함.xlsx";

const buf = readFileSync(DEFAULT_XLSX);
const wb = xlsxRead(buf, { type: "buffer" });
const sheetName = wb.SheetNames[0];
const rows = xlsxUtils.sheet_to_json(wb.Sheets[sheetName], { raw: true });

if (rows.length === 0) {
  console.error("No rows found in xlsx.");
  process.exit(1);
}

const VALID_CATEGORIES = new Set(["문학", "과학", "사회", "인문"]);

const books = rows.map((r, idx) => {
  const id = Number(r["No."] ?? idx + 1);
  const category = String(r["분류"] ?? "").trim();
  if (!VALID_CATEGORIES.has(category)) {
    console.warn(`Row ${id}: unexpected category "${category}"`);
  }
  return {
    id,
    title: String(r["서명"] ?? "").trim(),
    author: String(r["작가"] ?? "").trim(),
    publisher: String(r["출판사"] ?? "").trim(),
    year: Number(r["발행연도"] ?? 0),
    category,
    ondokIndex: Number(r["온독지수"] ?? 0),
    coverUrl: String(r["표지URL"] ?? "").trim(),
    description: String(r["책소개"] ?? "").trim(),
    naverLink: String(r["네이버링크"] ?? "").trim(),
    isbn: String(r["네이버ISBN"] ?? "").trim(),
  };
});

// Sanity checks
const missing = books.filter(
  (b) => !b.title || !b.coverUrl || !b.description || !b.naverLink
);
if (missing.length) {
  console.warn(
    `Warning: ${missing.length} book(s) missing required fields. IDs:`,
    missing.map((b) => b.id)
  );
}

// Emit JSON
const jsonOut = resolve(root, "src/data/books-seed.json");
mkdirSync(dirname(jsonOut), { recursive: true });
writeFileSync(jsonOut, JSON.stringify(books, null, 2), "utf8");

// Emit SQL upsert (one statement per row for readability)
const sqlEscape = (s) => s.replace(/'/g, "''");
const sqlLines = books.map((b) => {
  return `(${b.id}, '${sqlEscape(b.title)}', '${sqlEscape(b.author)}', '${sqlEscape(b.publisher)}', ${b.year}, '${sqlEscape(b.category)}', ${b.ondokIndex}, '${sqlEscape(b.coverUrl)}', '${sqlEscape(b.description)}', '${sqlEscape(b.naverLink)}', '${sqlEscape(b.isbn)}')`;
});
const sql = `-- 충남교육청 온독지수 추천도서 시드
-- Generated by scripts/xlsx-to-json.mjs from xlsx source.
-- Run AFTER creating the books table (see scripts/books-schema.sql).

INSERT INTO public.books (id, title, author, publisher, year, category, ondok_index, cover_url, description, naver_link, isbn)
VALUES
${sqlLines.join(",\n")}
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  author = EXCLUDED.author,
  publisher = EXCLUDED.publisher,
  year = EXCLUDED.year,
  category = EXCLUDED.category,
  ondok_index = EXCLUDED.ondok_index,
  cover_url = EXCLUDED.cover_url,
  description = EXCLUDED.description,
  naver_link = EXCLUDED.naver_link,
  isbn = EXCLUDED.isbn;
`;
const sqlOut = resolve(root, "scripts/books-seed.sql");
writeFileSync(sqlOut, sql, "utf8");

console.log(`✓ Wrote ${books.length} books`);
console.log(`  → ${jsonOut}`);
console.log(`  → ${sqlOut}`);

// Stats
const byCategory = books.reduce((acc, b) => {
  acc[b.category] = (acc[b.category] || 0) + 1;
  return acc;
}, {});
console.log(`\nBy category:`, byCategory);
const minIdx = Math.min(...books.map((b) => b.ondokIndex));
const maxIdx = Math.max(...books.map((b) => b.ondokIndex));
console.log(`Ondok index range: ${minIdx} ~ ${maxIdx}`);
